packages:
  - demo/*
  - docs/*
  - docs-shared/
  - packages/*

catalog:
  "@vueuse/core": ^12.2.0
  "@vuepress/bundler-vite": 2.0.0-rc.19
  "@vuepress/bundler-webpack": 2.0.0-rc.19
  "@vuepress/helper": 2.0.0-rc.66
  "@vuepress/plugin-revealjs": 2.0.0-rc.66
  "@vuepress/theme-default": 2.0.0-rc.66
  sass: ^1.81.0
  sass-embedded: ^1.81.0
  sass-loader: ^16.0.4
  vue: ^3.5.13
  vuepress: 2.0.0-rc.19

catalogs:
  latest:
    "@vueuse/core": 12.2.0
    katex: 0.16.18
    rollup: 4.29.1
    sass-embedded: 1.83.0
    sass-loader: 16.0.4
    vue: 3.5.13
